name: Notification Service

on:
  push:
    paths:
      - notification-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./notification-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      - name: Start Docker for Testcontainers
        run: |
          sudo service docker start
          docker --version

      - name: Build with Maven
        run: ./mvnw -ntp verify